#https://resocoder.com/2019/08/29/flutter-tdd-clean-architecture-course-2-entities-use-cases/

name: clean_tdd_numbers
description: Clean TDD app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # Service Locator
  get_it: ^7.2.0 #^2.0.1

  #Bloc for state router_management
  flutter_bloc: ^8.0.1 #^0.21.0

  #Bloc test:
  bloc_test: ^9.0.3

  #value equality equatable
  equatable: ^2.0.3 #^0.4.0

  # Functional programming thingies
  dartz: ^0.10.1 #^0.8.6

  # Remote API
  connectivity_plus: ^2.2.1 # connectivity iun the example
  http: ^0.13.4 #^0.12.0+2

  # Local cache
  shared_preferences: ^2.0.15 #^0.5.3+4

  #Mocktail new mocking lib
  mocktail: ^0.3.0

  #Data connection checker
  internet_connection_checker: ^0.0.1+3

  #Sembast NO-SQL Local DB
  #sembast: ^3.2.0

  flutter_riverpod: ^2.0.0-dev.7

  state_notifier_test: ^0.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  #mockito: ^5.1.0 #^4.1.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
